virtualbox:
  defaults:
    batch_size: 1
    ssh_username: vagrant
    box: trusty64
    box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box

  vbox_wifi:
    nic: eth1
    nic_name: "en0: Wi-Fi (AirPort)"
